import importlib
import pkgutil
import sys
import unittest
from pathlib import Path
from types import SimpleNamespace
from unittest.mock import MagicMock, patch

from sqlalchemy import create_engine
from sqlalchemy.orm import sessionmaker


AGENT_SRC = Path(__file__).resolve().parents[1] / "ai-agent" / "src"
if str(AGENT_SRC) not in sys.path:
    sys.path.insert(0, str(AGENT_SRC))

import app.models
from ai_agent.config import settings as agent_settings
from ai_agent.provider import ProviderError, ProviderResult
from ai_agent.tasks import _generate_job_payload
from app.core.config import settings
from app.database import Base
from app.models.ai_exam import AIQuestionDraft
from app.models.billing import AIQCUsage, TeacherQCWallet
from app.models.role import Role
from app.models.user import User
from app.services.ai_exam_service import (
    complete_ai_agent_job,
    create_ai_exam_generation_job,
    fail_ai_agent_job,
    prepare_ai_agent_dispatch,
)


for module in pkgutil.iter_modules(app.models.__path__):
    importlib.import_module(f"app.models.{module.name}")


def _question(
    number: int,
    question_type: str,
    difficulty: str,
) -> dict:
    options = ["A", "B", "C", "D"] if question_type == "multiple_choice" else []
    correct_answer = "A"
    if question_type == "true_false":
        correct_answer = True
    elif question_type == "short_answer":
        correct_answer = ["365", "365 giay"]
    elif question_type == "essay":
        correct_answer = None
    return {
        "type": question_type,
        "content": f"Question {number}",
        "options": options,
        "correct_answer": correct_answer,
        "explanation": "Explanation and scoring guidance",
        "difficulty": difficulty,
        "points": 1,
        "topic": "Vat ly 10",
    }


class AIAgentPipelineTests(unittest.TestCase):
    def setUp(self) -> None:
        self.engine = create_engine("sqlite:///:memory:")
        Base.metadata.create_all(self.engine)
        self.Session = sessionmaker(bind=self.engine)
        self.db = self.Session()

        role = Role(name="teacher")
        self.db.add(role)
        self.db.flush()
        self.teacher = User(
            role_id=role.id,
            full_name="Teacher Agent Test",
            username="teacher-agent-test",
            email="teacher-agent@example.com",
            email_verified=True,
        )
        self.db.add(self.teacher)
        self.db.commit()
        self.db.refresh(self.teacher)

        self.original_cost = settings.AI_QC_COST_PER_QUESTION
        self.original_welcome_qc = settings.TEACHER_WELCOME_QC
        settings.AI_QC_COST_PER_QUESTION = 1
        settings.TEACHER_WELCOME_QC = 30

    def tearDown(self) -> None:
        settings.AI_QC_COST_PER_QUESTION = self.original_cost
        settings.TEACHER_WELCOME_QC = self.original_welcome_qc
        self.db.close()
        self.engine.dispose()

    def test_agent_generation_callback_saves_all_four_types_and_charges_qc(self) -> None:
        request_data = self._request_data(
            question_count=4,
            question_types=["multiple_choice", "true_false", "short_answer", "essay"],
            type_distribution={
                "multiple_choice": 1,
                "true_false": 1,
                "short_answer": 1,
                "essay": 1,
            },
            difficulty_distribution={"easy": 1, "medium": 2, "hard": 1},
        )
        backend_job, _ = create_ai_exam_generation_job(
            self.db,
            self.teacher,
            request_data,
            idempotency_key="pipeline-success",
        )
        dispatch = prepare_ai_agent_dispatch(self.db, backend_job.id, "initial")
        provider_payload = {
            "title": "De thi Vat ly 10",
            "description": "Generated by the Agent",
            "subject": "Vat ly",
            "grade": "10",
            "duration_minutes": 45,
            "total_points": 4,
            "questions": [
                _question(1, "multiple_choice", "easy"),
                _question(2, "true_false", "medium"),
                _question(3, "short_answer", "medium"),
                _question(4, "essay", "hard"),
            ],
        }
        agent_job = self._agent_job(dispatch, backend_job.id)

        with patch("ai_agent.tasks._set_progress"), patch(
            "ai_agent.tasks.get_provider"
        ) as get_provider:
            get_provider.return_value.generate.return_value = ProviderResult(
                payload=provider_payload,
                raw_response={"mock": True},
                attempts=1,
            )
            result, raw_response = _generate_job_payload(MagicMock(), agent_job)

        completed = complete_ai_agent_job(
            self.db,
            backend_job.id,
            dispatch["dispatch_id"],
            "initial",
            result,
            raw_response,
            "gemini",
            "gemini-test",
        )

        usage = self.db.query(AIQCUsage).one()
        wallet = self.db.query(TeacherQCWallet).one()
        drafts = self.db.query(AIQuestionDraft).order_by(AIQuestionDraft.order).all()
        self.assertEqual(completed.status, "completed")
        self.assertEqual(usage.status, "charged")
        self.assertEqual(usage.qc_charged, 4)
        self.assertEqual(wallet.balance, 26)
        self.assertEqual(
            [draft.question_type for draft in drafts],
            ["multiple_choice", "true_false", "short_answer", "essay"],
        )

    def test_two_failed_semantic_repairs_end_job_and_refund_qc(self) -> None:
        request_data = self._request_data(
            question_count=1,
            question_types=["true_false"],
            type_distribution={"true_false": 1},
            difficulty_distribution={"easy": 1},
        )
        backend_job, _ = create_ai_exam_generation_job(
            self.db,
            self.teacher,
            request_data,
            idempotency_key="pipeline-failure",
        )
        dispatch = prepare_ai_agent_dispatch(self.db, backend_job.id, "initial")
        invalid_payload = {
            "title": "Invalid exam",
            "description": "Invalid true false answer",
            "subject": "Vat ly",
            "grade": "10",
            "duration_minutes": 45,
            "total_points": 1,
            "questions": [
                {
                    **_question(1, "true_false", "easy"),
                    "correct_answer": "maybe",
                }
            ],
        }
        agent_job = self._agent_job(dispatch, backend_job.id)

        with patch.object(agent_settings, "SEMANTIC_REPAIR_COUNT", 2), patch(
            "ai_agent.tasks._set_progress"
        ), patch("ai_agent.tasks.get_provider") as get_provider:
            get_provider.return_value.generate.return_value = ProviderResult(
                payload=invalid_payload,
                raw_response={"mock": True},
                attempts=1,
            )
            with self.assertRaises(ProviderError) as raised:
                _generate_job_payload(MagicMock(), agent_job)

        failed = fail_ai_agent_job(
            self.db,
            backend_job.id,
            dispatch["dispatch_id"],
            "initial",
            [str(raised.exception)],
        )

        usage = self.db.query(AIQCUsage).one()
        wallet = self.db.query(TeacherQCWallet).one()
        self.assertEqual(get_provider.return_value.generate.call_count, 3)
        self.assertEqual(failed.status, "failed")
        self.assertEqual(usage.status, "refunded")
        self.assertEqual(usage.qc_refunded, 1)
        self.assertEqual(wallet.balance, 30)
        self.assertEqual(self.db.query(AIQuestionDraft).count(), 0)

    @staticmethod
    def _request_data(
        question_count: int,
        question_types: list[str],
        type_distribution: dict[str, int],
        difficulty_distribution: dict[str, int],
    ) -> dict:
        return {
            "subject": "Vat ly",
            "grade": "10",
            "topic": "Tao de 15 phut ve Vat ly lop 10",
            "duration_minutes": 45,
            "question_count": question_count,
            "question_types": question_types,
            "question_type_distribution": type_distribution,
            "difficulty_distribution": difficulty_distribution,
            "language": "Vietnamese",
            "additional_instructions": "",
        }

    @staticmethod
    def _agent_job(dispatch: dict, backend_job_id: int) -> SimpleNamespace:
        return SimpleNamespace(
            id=f"agent-{backend_job_id}",
            prompt=dispatch["prompt"],
            request_data=dispatch["request_data"],
            attempt_count=0,
        )


if __name__ == "__main__":
    unittest.main()
